export const integrations = [
  {
    name: 'Shopify',
    mark: 'S',
    color: '#6b9e3e',
    category: 'Commerce',
    description: 'Sync your product catalog, storefront, and checkout flows.',
    status: 'Connected',
    detail: 'Last synced 4 minutes ago',
  },
  {
    name: 'CommerceTools',
    mark: 'ct',
    color: '#6350d5',
    category: 'Commerce',
    description: 'Test headless commerce APIs and composable shopping journeys.',
    status: 'Available',
    detail: 'Commerce API connector',
  },
  {
    name: 'Stripe',
    mark: 'S',
    color: '#635bff',
    category: 'Payments',
    description: 'Validate agent checkout flows in your payment sandbox.',
    status: 'Available',
    detail: 'Test-mode payments',
  },
  {
    name: 'Adyen',
    mark: 'adyen',
    color: '#0c9e65',
    category: 'Payments',
    description: 'Observe payment authorization and checkout completion.',
    status: 'Available',
    detail: 'Payment flow connector',
  },
  {
    name: 'Cloudflare',
    mark: '☁',
    color: '#ed8b26',
    category: 'Infrastructure',
    description: 'Connect agent identity signals with your edge security policies.',
    status: 'Available',
    detail: 'WAF and bot management',
  },
  {
    name: 'Vercel',
    mark: '▲',
    color: '#181b24',
    category: 'Infrastructure',
    description: 'Run readiness checks against every preview deployment.',
    status: 'Available',
    detail: 'Deployment checks',
  },
  {
    name: 'GitHub',
    mark: 'GH',
    color: '#252b37',
    category: 'Development',
    description: 'Turn findings into issues and verify fixes in pull requests.',
    status: 'Connected',
    detail: 'evertrail/storefront · 1 repository',
  },
  {
    name: 'Datadog',
    mark: 'D',
    color: '#7446a9',
    category: 'Observability',
    description: 'Correlate shopping sessions with your application traces.',
    status: 'Available',
    detail: 'Traces and events',
  },
  {
    name: 'CI/CD Webhook',
    mark: '</>',
    color: '#527393',
    category: 'Development',
    description: 'Trigger scans from your pipeline and enforce readiness gates.',
    status: 'Configured',
    detail: 'Last delivery 26 minutes ago',
  },
];
export const ciCommand =
  'gateway scan \\\n  --site evertrailoutdoors.com \\\n  --environment staging \\\n  --fail-below 70';
